const jogadorasFemininas = [
    {
        "id": 33,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/michelle",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/33.png",
        "n_jogos": "16 JOGOS",
        "nome": "MICHELLE CHRISTINA CERQUEIRA GOMES LOPES",
        "posicao": "Goleira",
        "naturalidade": "Rio de Janeiro (RJ)",
        "nascimento": "24/11/1989",
        "altura": "",
        "no_botafogo_desde": "2024",
        "detalhes": "Michelle é uma goleira excepcional que desempenha um papel fundamental na defesa do Botafogo. Com sua presença segura e habilidades técnicas, ela se destaca como uma das principais guardiãs da equipe. Possui reflexos rápidos, agilidade e coragem, é capaz de realizar defesas incríveis e decisivas, protegendo a meta de sua equipe em momentos críticos do jogo. Sua capacidade de ler o jogo e antecipar os movimentos dos adversários é uma vantagem valiosa, permitindo-lhe interceptar cruzamentos perigosos e evitar gols."
    },
    {
        "id": 34,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/yasmim",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/34.png",
        "n_jogos": "32 JOGOS",
        "nome": "YASMIM CRISTINA SEABRA PEREIRA",
        "posicao": "Goleira",
        "naturalidade": "Rio de Janeiro (RJ)",
        "nascimento": "11/06/1995",
        "altura": "",
        "no_botafogo_desde": "2022",
        "detalhes": "A arqueira se destaca pela boa imposição física, experiência e muita técnica. Yasmim é a responsável por fechar o gol das Gloriosas e pelas grandes defesas.\n "
    },
    {
        "id": 35,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/maria-alyce",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/35.png",
        "n_jogos": "1 JOGOS",
        "nome": "MARIA ALYCE SILVA",
        "posicao": "Goleira",
        "naturalidade": "Aperibé (RJ)",
        "nascimento": "02/03/2003",
        "altura": "",
        "no_botafogo_desde": "2023",
        "detalhes": "Maria Alyce chegou ao clube em janeiro de 2023 para compor o elenco das #CriasGloriosas e foi chamada para a equipe principal feminina após excelentes atuações nos treinos da categoria sub-20. Tem como ponto forte sua excelente saída de bola e segurança aérea.\n "
    },
    {
        "id": 36,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/chai",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/36.png",
        "n_jogos": "89 JOGOS",
        "nome": "CHAIANE LOCATELLI",
        "posicao": "Lateral esquerda",
        "naturalidade": "Garibaldi (RS)",
        "nascimento": "20/02/1995",
        "altura": "",
        "no_botafogo_desde": "2020",
        "detalhes": "Lateral direita de técnica apurada, comprometida com a equipe e diferenciada nas bolas paradas. Chai está entrando na terceira temporada e faz parte do grupo das atletas que conquistaram o acesso para a série A1 em 2020. A atleta é peça essencial da equipe."
    },
    {
        "id": 37,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/raiani-cruz",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/37.png",
        "n_jogos": "0 JOGOS",
        "nome": "RAIANI DA CRUZ CAETANO GOMES",
        "posicao": "Zagueira",
        "naturalidade": "São Paulo (RJ)",
        "nascimento": "13/04/2003",
        "altura": "",
        "no_botafogo_desde": "2022",
        "detalhes": "Com uma combinação de força física, agilidade e habilidade técnica, Raiani tem a capacidade de neutralizar os ataques adversários e fazer lançamentos precisos para iniciar jogadas de contra-ataque. Sua presença firme na linha defensiva proporciona estabilidade e segurança à equipe, enquanto sua visão de jogo apurada lhe permite antecipar as jogadas dos adversários."
    },
    {
        "id": 38,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/guima",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/38.png",
        "n_jogos": "4 JOGOS",
        "nome": "ANA CLARA PEREIRA GUIMARÃES",
        "posicao": "Lateral esquerda",
        "naturalidade": "São Gonçalo (RJ)",
        "nascimento": "11/02/2004",
        "altura": "",
        "no_botafogo_desde": "2023",
        "detalhes": "Guima chegou à equipe feminina em janeiro de 2023 para compor o elenco das #CriasGloriosas. É conhecida por sua qualidade em bolas paradas e pela sua frequência nas convocações para a Seleção Brasileira Feminina Sub-20."
    },
    {
        "id": 39,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/karen",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/39.png",
        "n_jogos": "102 JOGOS",
        "nome": "KÁREN BENDER",
        "posicao": "Zagueira",
        "naturalidade": "Passo Fundo (RS)",
        "nascimento": "21/02/1996",
        "altura": "",
        "no_botafogo_desde": "2020",
        "detalhes": "Káren se destaca na zaga Gloriosa pelo seu cabeceio e garra nas disputas de bola. A atleta conta com passagens em clubes nacionais e internacionais, além de fazer parte do elenco que garantiu o acesso para a série A1 na temporada 2020. No ano de 2022, a zagueira conquistou o segundo título Carioca do Glorioso."
    },
    {
        "id": 40,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/leticia-debiasi",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/40.png",
        "n_jogos": "4 JOGOS",
        "nome": "LETICIA DEBIASI",
        "posicao": "Zagueira",
        "naturalidade": "Machadinho (RS)",
        "nascimento": "17/09/2003",
        "altura": "",
        "no_botafogo_desde": "2022",
        "detalhes": "Cria da base alvinegra, Letícia se destaca pela sua força e visão de jogo. Com o Botafogo, conquistou o bicampeonato carioca sub-20, campeã da Taça Unifoot na temporada de 2023 e o título da Copa Rio Profissional, em 2024."
    },
    {
        "id": 41,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/kewllen",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/41.png",
        "n_jogos": "22 JOGOS",
        "nome": "KEWLLEN BATISTA BRITO",
        "posicao": "Meio-Campista",
        "naturalidade": "Manaus (AM)",
        "nascimento": "13/04/2003",
        "altura": "1.75",
        "no_botafogo_desde": "2022",
        "detalhes": "Kewllen possui um excelente controle de bola e uma capacidade impressionante de distribuir passes precisos, o que a torna uma peça-chave na construção das jogadas ofensivas. Além disso, sua capacidade de interceptação e marcação firme faz dela uma adversária formidável para os oponentes, contribuindo significativamente para a solidez defensiva da equipe."
    },
    {
        "id": 42,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/barbara-melo",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/42.png",
        "n_jogos": "12 JOGOS",
        "nome": "BÁRBARA SANTOS DE MELO",
        "posicao": "Lateral direita",
        "naturalidade": "Maceió (AL)",
        "nascimento": "23/08/1999",
        "altura": "1.61",
        "no_botafogo_desde": "2024",
        "detalhes": "Bárbara é uma lateral que não domina não apenas a linha defensiva, mas também desempenha um papel crucial no apoio ao ataque de sua equipe. Com uma combinação de velocidade, técnica e inteligência tática, se destaca como uma das melhores em sua posição."
    },
    {
        "id": 43,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/duda-basilio",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/43.png",
        "n_jogos": "15 JOGOS",
        "nome": "MARIA EDUARDA BASÍLIO TEIXEIRA",
        "posicao": "Meio-Campista",
        "naturalidade": "Rio de Janeiro (RJ)",
        "nascimento": "15/09/2003",
        "altura": "1.58",
        "no_botafogo_desde": "2023",
        "detalhes": "Meia de um toque refinado e precisão nos passes, Duda é hábil em criar oportunidades de gol para suas companheiras de equipe. Sua capacidade de ler o jogo e encontrar espaços vazios na defesa adversária faz dela uma jogadora versátil e perigosa no ataque. Além disso, sua agilidade e controle de bola permitem que ela conduza o jogo com maestria, driblando as oponentes e mantendo a posse de bola sob pressão."
    },
    {
        "id": 44,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/florencia-salazar",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/44.png",
        "n_jogos": "0 JOGOS",
        "nome": "FLORENCIA ELIZABETH SALAZAR",
        "posicao": "Zagueira",
        "naturalidade": "Merlo (BA)",
        "nascimento": "03/09/1993",
        "altura": "1.69",
        "no_botafogo_desde": "2024",
        "detalhes": "Com um estilo de jogo marcado pela força física e pela precisão técnica, Florencia se destaca como uma defensora implacável, capaz de neutralizar os ataques adversários com maestria. Sua agilidade e leitura de jogo afiada lhe permitem antecipar as jogadas dos oponentes e cortar passes com precisão cirúrgica."
    },
    {
        "id": 45,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/pamela",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/45.png",
        "n_jogos": "6 JOGOS",
        "nome": "PÂMELA FARIA LIMA DE VASCONCELOS",
        "posicao": "Atacante",
        "naturalidade": "Rio de Janeiro (RJ)",
        "nascimento": "03/09/1989",
        "altura": "1.64",
        "no_botafogo_desde": "2024",
        "detalhes": "Pâmela é uma atacante versátil que se destaca pelo seu domínio técnico e inteligência tática dentro de campo. Seu jogo é caracterizado por uma combinação de habilidades refinadas e uma compreensão táticas do jogo."
    },
    {
        "id": 46,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/jordana",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/46.png",
        "n_jogos": "13 JOGOS",
        "nome": "JORDANA SOARES DO SANTOS COUTO",
        "posicao": "Meio-Campista",
        "naturalidade": "Salvador (BA)",
        "nascimento": "13/04/2000",
        "altura": "1.63",
        "no_botafogo_desde": "2024",
        "detalhes": "Jordana é uma volante determinada e incansável que desempenha um papel fundamental na equipe do Botafogo. Com sua presença firme no meio-campo, ela se destaca pela sua capacidade de quebrar as jogadas adversárias e proteger a defesa com eficiência."
    },
    {
        "id": 47,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/silvana",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/47.png",
        "n_jogos": "7 JOGOS",
        "nome": "SILVANA DE JESUS BISPO",
        "posicao": "Zagueira",
        "naturalidade": "Salvador (BA)",
        "nascimento": "18/02/1998",
        "altura": "1.79",
        "no_botafogo_desde": "2024",
        "detalhes": "Silvana é uma zagueira talentosa e confiável que desempenha um papel crucial na defesa do Botafogo. Com sua presença imponente e sua habilidade técnica, ela se destaca como uma das principais defensoras da equipe."
    },
    {
        "id": 48,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/gabi-itacare",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/48.png",
        "n_jogos": "14 JOGOS",
        "nome": "GABRIELLE DA SILVA SANTOS",
        "posicao": "Atacante",
        "naturalidade": "Itacaré (BA)",
        "nascimento": "16/03/1995",
        "altura": "1.74",
        "no_botafogo_desde": "2024",
        "detalhes": "Gabi Itacaré é uma centroavante talentosa e destemida que desempenha um papel crucial no ataque do Botafogo. Ela se destaca como uma das principais finalizadoras da equipe."
    },
    {
        "id": 49,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/drika",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/49.png",
        "n_jogos": "37 JOGOS",
        "nome": "ADRIANA FERREIRA DA SILVA",
        "posicao": "Atacante",
        "naturalidade": "Codó - MA",
        "nascimento": "12/01/1998",
        "altura": "1.58",
        "no_botafogo_desde": "2023",
        "detalhes": "Natural do Maranhão, Drika se destaca em campo pela sua velocidade e agilidade em transitar na defesa adversária. Seu chute forte também é uma característica marcante em seu jogo."
    },
    {
        "id": 50,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/luciana-gomez",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/50.png",
        "n_jogos": "7 JOGOS",
        "nome": "LUCIANA DANIELA GOMEZ MONTANS",
        "posicao": "Meio-Campista",
        "naturalidade": "Montevideo",
        "nascimento": "06/08/2000",
        "altura": "1.7",
        "no_botafogo_desde": "2024",
        "detalhes": "Luciana Gómez é uma meia talentosa e versátil, cuja habilidade e visão de jogo são verdadeiros destaques em campo. Sua capacidade de controlar o jogo no meio-campo e criar oportunidades de gol é notável, tornando-a uma peça fundamental em qualquer equipe."
    },
    {
        "id": 51,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/nathane",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/51.png",
        "n_jogos": "17 JOGOS",
        "nome": "NATHANE CADORINI FABEM",
        "posicao": "Atacante",
        "naturalidade": "São Mateus (ES)",
        "nascimento": "06/08/1990",
        "altura": "1.72",
        "no_botafogo_desde": "2024",
        "detalhes": "Nathane é conhecida dentro e fora de campo por sua resiliência. A camisa 9 das #Gloriosas colabora com o grupo marcando gols e dando assistências para as companheiras. Sua força e intensidade são dominantes e resulta na felicidade da equipe alvinegra."
    },
    {
        "id": 52,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/vitorinha",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/52.png",
        "n_jogos": "23 JOGOS",
        "nome": "JOSEFA VICTORIA DA SILVA SOUZA",
        "posicao": "Meio-Campista",
        "naturalidade": "Palmares (AL)",
        "nascimento": "14/08/1999",
        "altura": "1.61",
        "no_botafogo_desde": "2022",
        "detalhes": "A atleta chegou ao Glorioso em 2022 para agregar a equipe com sua técnica. Vitorinha é o tipo de volante clássica nas jogadas e de visão apurada, comanda o meio campo. "
    },
    {
        "id": 53,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/mayara-vaz",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/53.png",
        "n_jogos": "61 JOGOS",
        "nome": "MAYARA ANDREIA VAZ MOREIRA",
        "posicao": "Meio-Campista",
        "naturalidade": "Belém (PA)",
        "nascimento": "22/04/1995",
        "altura": "1.6",
        "no_botafogo_desde": "2022",
        "detalhes": "Conhecida como o motorzinho da equipe, Mayara possui  agilidade e velocidade com a bola nos pés. Meia experiente, possui passagem em clubes importantes no Brasil e China."
    },
    {
        "id": 54,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/nalon",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/54.png",
        "n_jogos": "47 JOGOS",
        "nome": "NATALIE GABRIELI NALON",
        "posicao": "Zagueira",
        "naturalidade": "Bituruna (PR)",
        "nascimento": "21/09/2002",
        "altura": "1.69",
        "no_botafogo_desde": "2022",
        "detalhes": "Após período na categoria Sub-20 das Gloriosas, a zagueira agrega a equipe principal e tem como característica sua força no combate com as adversárias."
    },
    {
        "id": 55,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/kelen",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/55.png",
        "n_jogos": "110 JOGOS",
        "nome": "KÉLEN BENDER",
        "posicao": "Atacante",
        "naturalidade": "Passo Fundo (RS)",
        "nascimento": "21/02/1996",
        "altura": "1.76",
        "no_botafogo_desde": "2020",
        "detalhes": "A trajetória de Kelen no futebol iniciou em um campo de terra e de pés descalços, assim como a maioria das atletas. A atacante se destaca pela sua velocidade, habilidade, cabeceio e finalização. A atleta chegou ao Botafogo no ano de 2019, conquistando o acesso para a série A1 em 2020 e conta com dois títulos Carioca. "
    },
    {
        "id": 56,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/jessica-bahia",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/56.png",
        "n_jogos": "3 JOGOS",
        "nome": "JESSICA ALVES SOUSA",
        "posicao": "Lateral direita",
        "naturalidade": "Salvador (BA)",
        "nascimento": "23/08/1991",
        "altura": "1.7",
        "no_botafogo_desde": "2023",
        "detalhes": "Jéssica chama a atenção na lateral direita por sua velocidade e agilidade. Iniciou sua trajetória no campo mais tradicional das crianças: a rua. Incentivada pelo ex-treinador e pela família, passou por um teste no São Francisco do Conde (BA), seu primeiro clube. A lateral chega ao Botafogo após duas temporadas no Fluminense."
    },
    {
        "id": 57,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/vania",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/57.png",
        "n_jogos": "41 JOGOS",
        "nome": "ELISVÂNIA DE PAZ DE SOUSA",
        "posicao": "Atacante",
        "naturalidade": "Codó (MA)",
        "nascimento": "27/06/2002",
        "altura": "1.56",
        "no_botafogo_desde": "2022",
        "detalhes": "Vânia iniciou sua trajetória no Menina Olímpica, projeto social localizado no Maranhão e chegou ao Botafogo em 2022 para fazer parte da equipe Sub-20. A atleta se destaca pela sua velocidade e boa finalização."
    },
    {
        "id": 58,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/driely",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/58.png",
        "n_jogos": "96 JOGOS",
        "nome": "DRIELY SEVERINO FERREIRA",
        "posicao": "Meio-Campista",
        "naturalidade": "Formosas (GO)",
        "nascimento": "06/07/1990",
        "altura": "1.66",
        "no_botafogo_desde": "2020",
        "detalhes": "Conhecida pela sua garra nas disputas de bola, a experiente volante é respeitada por toda a equipe. A jogadora fez parte do elenco do São Paulo na conquista do Campeonato Brasileiro A2."
    },
    {
        "id": 59,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/bruna-souza",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/59.png",
        "n_jogos": "95 JOGOS",
        "nome": "BRUNA DE SOUZA DOS SANTOS",
        "posicao": "Lateral direita",
        "naturalidade": "São Paulo (SP)",
        "nascimento": "14/12/2000",
        "altura": "",
        "no_botafogo_desde": "2021",
        "detalhes": "Apaixonada por futebol desde criança, Bruna iniciou sua trajetória jogando com os meninos. Foram 5 anos fazendo parte de escolinhas até chegar ao Centro Olímpico. Lateral voluntariosa de muita força e de extrema regularidade. Chegou ao Glorioso em agosto de 2018, conquistou o acesso para a série A1 em 2020 e dois títulos cariocas nos últimos anos."
    },
    {
        "id": 60,
        "url_detalhes": "https://botafogo.com.br/elenco/futebol-feminino/japa",
        "elenco": "feminino",
        "imagem": "https://botafogo-atletas.mange.li/static/2024-1/60.png",
        "n_jogos": "28 JOGOS",
        "nome": "ANA PAULA EMY SATAKE YAMADA",
        "posicao": "Meio-Campista",
        "naturalidade": "São Paulo (SP)",
        "nascimento": "11/06/2002",
        "altura": "",
        "no_botafogo_desde": "2022",
        "detalhes": "Japa se destaca pela sua inteligência nas tomadas de decisão e técnica apurada. Chegou no Botafogo para a categoria Sub-20, onde conquistou o título inédito de campeã Carioca em 2022. Na temporada 2023, a meia compõe a equipe principal das Gloriosas."
    }
]